config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'home/index'

  root 'home#index'
  get 'home/mission_vision'
  get 'home/founders'
  get 'home/principal_message'
  get 'home/committee'
  get 'home/committees'
  get 'home/faculty'
  get 'home/oasis'
  get 'home/result_date_sheet'
  get 'home/book_list'
  get 'home/admission_procedure'
  get 'home/prospectus'
  get 'home/fee_stracture'
  get 'home/student_strength'
  get 'home/tc_entries'
  get 'home/activities_compatitions'
  get 'home/school_building'
  get 'home/transport_facilities'
  get 'home/class_room'
  get 'home/infirmary'
  get 'home/library'
  get 'home/laboratories'
  get 'home/photos'
  get 'home/videos'
  get 'home/contact_us'
  get 'home/feedback'
  get 'home/about_us'
  get 'home/vacancy'
  get 'home/ptm'
  get 'home/public_disclosure'
  get 'home/extension_letter'
  get 'home/annual_report'

  resource :gallery_images, only: :show
  resource :gallery_videos, only: :show

  get 'home/affiliation_letter'
  get 'home/society_registration_certificate'
  get 'home/noc'
  get 'home/recognition_certificate'
  get 'home/building_safety_certificate'
  get 'home/fire_safety_certificate'
  get 'home/deo_certificate'
  get 'home/water_sanitation_certificate'
  get 'home/academic_calendar'
  get 'home/last_three_year_results'
  get 'home/norms_of_fixing_fee'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-12 col-lg-4 footer-col-4">
            <div class="widget widget_getintuch">
              <h4 class="footer-title">Contact Us</h4>
              <div class="dlab-separator bg-warning"></div>
              <ul class="info-contact">
                <li>
                  <span>
                  <i class="fa fa-map-marker"></i>
                  School Address:<br />
                  <a href="https://www.google.com/maps/embed/v1/place?key=AIzaSyAulkcv0Hp4voynS3RC2OwpGvAOrx64UB8&amp;q=Agra Bah Road, Udi Mod Etawah 206131, Uttar Pradesh, India" target="_blank" data-toggle="tooltip" data-placement="top"
                    title="Find On Google Map">
                  Agra Bah Road, Udi Mod Etawah 206131
                  </a>
                  </span>
                </li>
                <li>
                  <span>
                  <i class="fa fa-phone"></i>
                  Main Office:<br />
                  <a href="tel:+91-8533012547"
                    data-toggle="tooltip" data-placement="top" title="Office Superintendent">
                  +91-8533012547                                        </a>
                  </span>
                </li>
                <li>
                  <span>
                  <i class="fa fa-envelope-o"></i>
                  Email Address:<br />
                  <a href="mailto:sainikschooljhansi@gmail.com"
                    data-toggle="tooltip" data-placement="top" title="Send Us Email">
                  shakuntalam.official@gmail.com                                        </a>
                  </span>
                </li>
                <li>
                  <span>
                  <i class="fa fa-youtube"></i>
                  Subscribe Us:<br />
                  <a href="https://www.youtube.com/channel/UCi4McVcLbGzHHgO7u4qS6Nw" data-toggle="tooltip" data-placement="top"
                    title="Subscribe Our YouTube Channel">
                  Youtube Channel
                  </a>
                  </span>
                </li>
              </ul>
            </div>
          </div>
           <div class="col-md-8 col-sm-12 col-lg-8 footer-col-8 col-8">
            <div class="widget widget_services">
              <div class="elementor-custom-embed">
                <iframe width="100%" height="400" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAulkcv0Hp4voynS3RC2OwpGvAOrx64UB8&amp;q=Agra Bah Road, Udi Mod Etawah 206131, Uttar Pradesh, India" allowfullscreen></iframe>
              </div>
            </div>
          </div>
          <%#<div class="col-md-6 col-sm-6 col-lg-3 footer-col-4 col-6">
            <div class="widget widget_services">
              <h4 class="footer-title">Quick Links</h4>
              <div class="dlab-separator bg-warning"></div>
              <ul>
                <li><a href="https://sainikschooljhansi.com/infrastructure/smart-classroom">Infrastructures</a></li>
                <li><a href="https://sainikschooljhansi.com/labs/mathematics-lab">Labs</a></li>
                <li><a href="https://sainikschooljhansi.com/cadets/parent-guidelines">Cadets</a></li>
                <li><a href="https://sainikschooljhansi.com/photogallery">Photo Gallery</a></li>
                <li><a href="https://sainikschooljhansi.com/videogallery">Video Gallery</a></li>
                <li><a href="https://sainikschooljhansi.com/adminstaff">Admin Staff</a></li>
                <li><a href="https://sainikschooljhansi.com/academicstaff">Academic Staff</a></li>
                <li><a href="https://sainikschooljhansi.com/contactus">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-lg-3 footer-col-4">
            <div class="widget widget_services">
              <h4 class="footer-title">Page Links</h4>
              <div class="dlab-separator bg-warning"></div>
              <ul>
                <li><a href="https://sainikschooljhansi.com/newsletter">Newslatter</a></li>
                <li><a href="https://sainikschooljhansi.com/files/sanik-school-jhansi-book.pdf" target="_blank">School Magazine</a></li>
                <li><a href="https://sainikschooljhansi.com/cbsecompliance">CBSC Complaince</a></li>
                <li><a href="https://sainikschooljhansi.com/syllabus">Syllabus</a></li>
                <li><a href="https://aissee.ntaonline.in/" target="_blank">Registration Link</a></li>
                <li><a href="https://www.onlinesbi.sbi/sbicollect/icollecthome.htm" target="_blank">Online Fees Payment</a></li>
                <li><a href="https://sainikschooljhansi.com/ncc">NCC</a></li>
                <li><a href="https://sainikschooljhansi.com/nda">NDA</a></li>
              </ul>
            </div>
          </div> %>
        </div>
      </div>
    </div>
    <!-- footer bottom part -->
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-12 text-center">
            <p>
              &copy; Copyright <%= Time.now.year %> - Sainik School Shakuntlam Etawah, All Rights Reserved.
              <br />Design, Develop & Maintained By: <a href="https://startek.in/" target="_blank" class="text-warning">Vaibhav Dwivedi</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="site-header header mo-left">
    <!-- main header -->
    <div class="sticky-header main-bar-wraper navbar-expand-lg">
      <!-- Top Bar header -->
      <div class="topnav d-none d-lg-block d-md-block d-sm-block">
        <div class="container-fluid clearfix">
          <div class="row">
            <div class="col-4">
              <ul class="list-inline text-uppercase">
                <li class="list-inline-item pr-3">
                  <a href="https://sainikschooljhansi.com/newsletter">
                  <i class="fa fa-newspaper-o mr-2"></i>Newsletter</a>
                </li>
                <li class="list-inline-item pr-3">
                  <a href="#-"><i class="fa fa-book mr-2"></i>Syllabus</a>
                </li>
                <li class="list-inline-item">
                  <a href="<%= home_vacancy_path%>">
                  <i class="fa fa-check-circle mr-2"></i>Recruitments</a>
                </li>
              </ul>
            </div>
            <div class="col-4">
              <ul class="list-inline text-uppercase">
                <li class="list-inline-item pr-3">
                  <a href="#-" target="blank">
                  <i class="fa fa-file-pdf-o mr-2"></i>School Magazine</a>
                </li>
                <li class="list-inline-item">
                  <a href="#-">
                  <i class="fa fa-info-circle mr-2"></i>CBSE Complaince</a>
                </li>
                <li class="list-inline-item">
                  <a href="javascript:void;" data-fancybox data-options='{"type" : "iframe", "iframe" : {"preload" : true, "css" : {"width" : "100%"}}}' data-src="#-">
                  <i class="fa fa-file-pdf-o mr-2"></i>Academic Calendar</a>
                </li>
              </ul>
            </div>
            <div class="col-4">
              <ul class="list-inline text-uppercase">
                <%# <li class="list-inline-item pr-3">
                  <a href="javascript:void;" data-toggle="modal" data-target="#paymentmodal">
                  <i class="fa fa-credit-card mr-2"></i>Online Fees Payment</a>
                </li %>>
                <li class="list-inline-item pl-3">
                  <a href="https://aissee.ntaonline.in/" target="_blank">
                    <%= image_tag "blinking_new.gif", alt:"New", style:"height:18px;width:auto"%> AISSEE 2024 Registration</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- Header Mobile -->
      <div class="middlenav-mobile d-sm-block d-lg-none d-md-none d-sm-none pt-2 pb-2" style="background-image:url('india-flag.jpg'); background-repeat:no-repeat; background-position:center center; background-size:cover">
        <div class="container clearfix">
          <div class="row">
            <div class="col-3">
              <a href="/" class="mr-3">
                <%= image_tag('logo.jpg', class: "custom-logo", alt: "", width: "6700", height: "1454", style: "width: 120px;") %>
              </a>					
            </div>
            <div class="col-8">
              <div class="textlogomobile">
                <h1>Sainik School Etawah</h1>
                <strong>education - knowledge - power [CBSE AFFIL : 2133495]</strong>
              </div>
            </div>
            <div class="col-1">							
              <button class="navbar-toggler collapsed navicon justify-content-end" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
              <span></span>
              </button>								
            </div>
          </div>
        </div>
      </div>
      <!-- Header Tablet -->
      <div class="middlenav d-none d-md-block d-lg-none d-sm-none" style="background: #fff url(/assets/india-flag.jpg) no-repeat center center; background-size:cover">
        <div class="container clearfix">
          <div class="row">
            <div class="col-2">
              <a href="/">
              <%= image_tag('logo.jpg', class: "custom-logo", alt: "", width: "6700", height: "1454", style: "width: 120px;") %>
              </a>					
            </div>
            <div class="col-8">
              <div class="textlogomd text-center">
                <h1>Sainik School Etawah</h1>
                <strong>education - knowledge - power [CBSE AFFIL : 2133495]</strong>
              </div>
            </div>
            <div class="col-2">				
              <button class="navbar-toggler collapsed navicon justify-content-end" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
              <span></span>
              </button>						
            </div>
          </div>
        </div>
      </div>
      <!-- Header Desktop -->
      <div class="middlenav d-none d-lg-block d-md-none d-sm-block" style="background: #fff url('india-flag.jpg') no-repeat center center; background-size:cover">
        <div class="container-fluid clearfix">
          <div class="row">
            <div class="col-3">
              <a href="<%= root_url %>" class="rightlogo mr-2">
                <%= image_tag('sainik_society_logo.png', class: "img-fluid", alt: "") %>
              </a>
            </div>
            <div class="col-6">
              <div class="textlogo text-center">
                <h1>Sainik School Etawah</h1>
                <h1 class="animate-charcter d-none">Sainik School Etawah</h1>
                <strong>education - knowledge - power [CBSE AFFIL : 2133495]</strong>
              </div>
            </div>
            <div class="col-3">
              <div class="float-right">
                <a href="<%= root_url %>" class="rightlogo mr-2">
                  <%= image_tag('sainik_society_logo.png', class: "img-fluid", alt: "") %>
                </a>
              </div>
            </div>
            <button class="navbar-toggler collapsed navicon justify-content-end" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span></span>
            <span></span>
            <span></span>
            </button>
          </div>
        </div>
      </div>
      <!-- Menu Bar -->
      <div class="main-bar clearfix ">
        <div class="container-fluid clearfix">
          <div class="row">
            <div class="col-12">
              <div class="header-nav navbar-collapse collapse" id="navbarNavDropdown">
                <ul id="nvmenu" class="nav navbar-nav">
                  <li><a href="/">Home</a></li>
                  <li class="smenu">
                    <a href="javascript:void">About Us<i class="fa fa-chevron-down"></i></a>
                    <ul class="sub-menu">
                      <li><a href="<%= home_about_us_path %>">About The School</a></li>
                      <li><a href="<%= home_principal_message_path %>">About Principal</a></li>
                      <li><a href="<%= home_faculty_path %>">Organisational Chart</a></li>
                      <li><a href="<%= home_founders_path %>">Founder Father</a></li>
                    </ul>
                  </li>
                  <li class="smenu">
                    <a href="javascript:void;">Infrastructure <i class="fa fa-chevron-down"></i></a>
                    <ul class="sub-menu">
                      <li><a href="#-">Smart Classroom</a></li>
                      <li><a href="#-">Library</a></li>
                      <li><a href="#-">Playground</a></li>
                      <li><a href="#-">Basketball Court</a></li>
                      <li><a href="#-">Hostel</a></li>
                      <li><a href="#-">Counsellor Room</a></li>
                      <li><a href="#-">Staff Room</a></li>
                      <li><a href="#-">Dining Hall</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <base  /> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />

    <meta name="description" content="Sainik School Shakuntlam Etawah - Education, Knowledge, Power - CBSE AFFIL : 2133495" />
    <meta property="og:title" content="Sainik School Shakuntlam Etawah - Education, Knowledge, Power - CBSE AFFIL : 2133495" />
    <meta property="og:description" content="Sainik School Shakuntlam Etawah - Education, Knowledge, Power - CBSE AFFIL : 2133495" />
    <meta property="og:image" content="http://sainikschooletawah.org/assets/logo-80c766e8996167eedd8bd64448fce9143c0aa46bc9035747df2951529d995495.jpg" />
    <meta name="format-detection" content="telephone=no">
    <link rel="icon" href="https://sainikschooljhansi.com/images/favicon.ico" type="image/x-icon" />
    <title>WELCOME TO OUR SCHOOL - Sainik School Shakuntlam Etawah, Sainik School Society, Ministery of Defence, Government of India. </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" />

    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">
 
<script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
    <script src="js/html5shiv.min.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <!-- STYLESHEETS -->
    <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Rubik:300,300i,400,400i,500,500i,700,700i,900,900i&amp;display=swap');
    </style>
    <style type="text/css">
      a {
        text-decoration: none !important;
      }
    </style>
  </head>

  <body id="bg">
    <%= render 'layouts/header' %>
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>